/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package flex2.compiler.mxml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_DESIGNLAYER = 1;
  /** RegularExpression Id. */
  int END_DESIGNLAYER = 2;
  /** RegularExpression Id. */
  int START_DECLARATIONS = 3;
  /** RegularExpression Id. */
  int END_DECLARATIONS = 4;
  /** RegularExpression Id. */
  int START_STYLE = 5;
  /** RegularExpression Id. */
  int END_STYLE = 6;
  /** RegularExpression Id. */
  int START_SCRIPT = 7;
  /** RegularExpression Id. */
  int END_SCRIPT = 8;
  /** RegularExpression Id. */
  int START_METADATA = 9;
  /** RegularExpression Id. */
  int END_METADATA = 10;
  /** RegularExpression Id. */
  int START_STATE = 11;
  /** RegularExpression Id. */
  int END_STATE = 12;
  /** RegularExpression Id. */
  int START_MODEL = 13;
  /** RegularExpression Id. */
  int END_MODEL = 14;
  /** RegularExpression Id. */
  int START_XML = 15;
  /** RegularExpression Id. */
  int END_XML = 16;
  /** RegularExpression Id. */
  int START_XMLLIST = 17;
  /** RegularExpression Id. */
  int END_XMLLIST = 18;
  /** RegularExpression Id. */
  int START_ARRAY = 19;
  /** RegularExpression Id. */
  int END_ARRAY = 20;
  /** RegularExpression Id. */
  int START_VECTOR = 21;
  /** RegularExpression Id. */
  int END_VECTOR = 22;
  /** RegularExpression Id. */
  int START_BINDING = 23;
  /** RegularExpression Id. */
  int END_BINDING = 24;
  /** RegularExpression Id. */
  int START_STRING = 25;
  /** RegularExpression Id. */
  int END_STRING = 26;
  /** RegularExpression Id. */
  int START_NUMBER = 27;
  /** RegularExpression Id. */
  int END_NUMBER = 28;
  /** RegularExpression Id. */
  int START_INT = 29;
  /** RegularExpression Id. */
  int END_INT = 30;
  /** RegularExpression Id. */
  int START_UINT = 31;
  /** RegularExpression Id. */
  int END_UINT = 32;
  /** RegularExpression Id. */
  int START_BOOLEAN = 33;
  /** RegularExpression Id. */
  int END_BOOLEAN = 34;
  /** RegularExpression Id. */
  int START_CLASS = 35;
  /** RegularExpression Id. */
  int END_CLASS = 36;
  /** RegularExpression Id. */
  int START_FUNCTION = 37;
  /** RegularExpression Id. */
  int END_FUNCTION = 38;
  /** RegularExpression Id. */
  int START_REMOTEOBJECT = 39;
  /** RegularExpression Id. */
  int END_REMOTEOBJECT = 40;
  /** RegularExpression Id. */
  int START_METHOD = 41;
  /** RegularExpression Id. */
  int END_METHOD = 42;
  /** RegularExpression Id. */
  int START_ARGUMENTS = 43;
  /** RegularExpression Id. */
  int END_ARGUMENTS = 44;
  /** RegularExpression Id. */
  int START_WEBSERVICE = 45;
  /** RegularExpression Id. */
  int END_WEBSERVICE = 46;
  /** RegularExpression Id. */
  int START_OPERATION = 47;
  /** RegularExpression Id. */
  int END_OPERATION = 48;
  /** RegularExpression Id. */
  int START_REQUEST = 49;
  /** RegularExpression Id. */
  int END_REQUEST = 50;
  /** RegularExpression Id. */
  int START_HTTPSERVICE = 51;
  /** RegularExpression Id. */
  int END_HTTPSERVICE = 52;
  /** RegularExpression Id. */
  int START_COMPONENT = 53;
  /** RegularExpression Id. */
  int END_COMPONENT = 54;
  /** RegularExpression Id. */
  int START_REPARENT = 55;
  /** RegularExpression Id. */
  int END_REPARENT = 56;
  /** RegularExpression Id. */
  int START_PRIVATE = 57;
  /** RegularExpression Id. */
  int END_PRIVATE = 58;
  /** RegularExpression Id. */
  int START_LIBRARY = 59;
  /** RegularExpression Id. */
  int END_LIBRARY = 60;
  /** RegularExpression Id. */
  int START_DEFINITION = 61;
  /** RegularExpression Id. */
  int END_DEFINITION = 62;
  /** RegularExpression Id. */
  int START_ELEMENT = 63;
  /** RegularExpression Id. */
  int CDATA = 64;
  /** RegularExpression Id. */
  int END_ELEMENT = 65;
  /** RegularExpression Id. */
  int SKIP_ELEMENT = 66;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<START_ELEMENT>",
    "<CDATA>",
    "<END_ELEMENT>",
    "\"DesignLayer\"",
    "\"/DesignLayer\"",
    "\"Declarations\"",
    "\"/Declarations\"",
    "\"Style\"",
    "\"/Style\"",
    "\"Script\"",
    "\"/Script\"",
    "\"Metadata\"",
    "\"/Metadata\"",
    "\"State\"",
    "\"/State\"",
    "\"Model\"",
    "\"/Model\"",
    "\"XML\"",
    "\"/XML\"",
    "\"XMLList\"",
    "\"/XMLList\"",
    "\"Array\"",
    "\"/Array\"",
    "\"Vector\"",
    "\"/Vector\"",
    "\"Binding\"",
    "\"/Binding\"",
    "\"String\"",
    "\"/String\"",
    "\"Number\"",
    "\"/Number\"",
    "\"int\"",
    "\"/int\"",
    "\"uint\"",
    "\"/uint\"",
    "\"Boolean\"",
    "\"/Boolean\"",
    "\"Class\"",
    "\"/Class\"",
    "\"Function\"",
    "\"/Function\"",
    "\"RemoteObject\"",
    "\"/RemoteObject\"",
    "\"method\"",
    "\"/method\"",
    "\"arguments\"",
    "\"/arguments\"",
    "\"WebService\"",
    "\"/WebService\"",
    "\"operation\"",
    "\"/operation\"",
    "\"request\"",
    "\"/request\"",
    "\"HTTPService\"",
    "\"/HTTPService\"",
    "\"Component\"",
    "\"/Component\"",
    "\"Reparent\"",
    "\"/Reparent\"",
    "\"Private\"",
    "<SKIP_ELEMENT>",
    "\"/Private\"",
    "\"Library\"",
    "\"/Library\"",
    "\"Definition\"",
    "\"/Definition\"",
  };

}
